"""Adicionando campo de imagem 

Revision ID: c8b670044492
Revises: 
Create Date: 2026-09-15 10:55:09.527052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b670044492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pokemons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_pokemon', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pokemons', schema=None) as batch_op:
        batch_op.drop_column('imagem_pokemon')

    # ### end Alembic commands ###
